### ISSUE TITLE
'Model' object has no attribute '_uses_dynamic_learning_phase'

### ISSUE THREAD

**Issue by caoyuanjie1996** [bojone/keras_lookahead#10]
Traceback (most recent call last):
  File "G:/yolov4-tiny-keras-master/train.py", line 266, in <module>
    lookahead.inject(model)
  File "G:\yolov4-tiny-keras-master\lookahead.py", line 29, in inject
    if model._uses_dynamic_learning_phase():
AttributeError: 'Model' object has no attribute '_uses_dynamic_learning_phase'

**Comment by wenfan-wenfan** [comment]
This may be due to a keras version mismatch, which I have also experienced. You can solve the problem in this way： 
   " pip install keras==2.2.4 " ；

**Comment by caoyuanjie1996** [comment]
> This may be due to a keras version mismatch, which I have also experienced. You can solve the problem in this way：
> " pip install keras==2.2.4 " ；

thnak you,i have been pip install keras 2.2.4,and it is successful.but lookahead look like not enough great for loss,maybe my epoch is too small
